[symbols]
exclude = [
    "towctrans_l",
    "towctrans",
    "_towctrans_r",
    "_Stack_Allocator_allocate_for_idle_static",
]

[symbols.powerpc]
# Nothing yet

[symbols.i386]
exclude = [
    "lrintl",
    "rintl",
    "llrintl",
    "expl",
    "ldexpl",
    "logl",
    "log10l",
    "expl",
    "_bsd_dwc_otg_driver",
    "scalbnl",
    "cacoshl",
    "acos",
    "acosl",
    "asin",
    "asinl",
    "atan",
    "atan2",
    "atan2l",
    "atanl",
    "ceill",
    "cos",
    "cosh",
    "coshl",
    "cosl",
    "exp",
    "expl",
    "fabsl",
    "floorl",
    "fmod",
    "fmodl",
    "frexp",
    "frexpl",
    "hypotl",
    "ldexp",
    "ldexpl",
    "log",
    "log10",
    "log10l",
    "logl",
    "modf",
    "modfl",
    "pow",
    "powl",
    "sin",
    "sinh",
    "sinhl",
    "sinl",
    "sqrt",
    "sqrtl",
    "tan",
    "tanh",
    "tanhl",
    "tanl",
]