#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# Company    : SLAC National Accelerator Laboratory
# ----------------------------------------------------------------------------
# Description : Tool to generate a CMake toolchain and configure builds.
# ----------------------------------------------------------------------------
# This file is part of the rtems-tools package. It is subject to
# the license terms in the LICENSE.txt file found in the top-level directory
# of this distribution and at:
#    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
# No part of the rtems-tools package, including this file, may be
# copied, modified, propagated, or distributed except according to the terms
# contained in the LICENSE.txt file.
# ----------------------------------------------------------------------------
import os
import sys
import argparse
import subprocess
import string

# This is the main toolchain fragment that is substituted with values from pkgconfig
TOOLCHAIN_FRAGMENT = \
"""
# WARNING: This toolchain was automatically generated by cmake-configure!
set(RTEMS_ARCH "${RTEMS_ARCH}")
set(RTEMS_BSP "${RTEMS_BSP}")
set(RTEMS_BSP_BASE "${RTEMS_BSP}")
set(RTEMS_BSP_FAMILY "${RTEMS_BSP_FAMILY}")
set(RTEMS_MAJOR "${RTEMS_MAJOR}")
set(RTEMS_MINOR "${RTEMS_MINOR}")
set(RTEMS_REVISION "${RTEMS_REVISION}")

# Core CMake definitions
#set(CMAKE_SYSTEM_NAME "RTEMS")
set(CMAKE_SYSTEM_PROCESSOR "$${RTEMS_ARCH}")
set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# As much as I want to use 'RTEMS' here, I can't! CMake complains about it and won't shut up!
set(CMAKE_SYSTEM_NAME "Linux")

set(RTEMS_TOOLS_TOP "${RTEMS_TOOLS_TOP}/bin")
set(RTEMS_TOP "${RTEMS_TOP}")

set(RTEMS_VERSION "$${RTEMS_MAJOR}.$${RTEMS_MINOR}.$${RTEMS_REVISION}")

# Used to determine compiler name, i.e. aarch64-rtems7-gcc
set(RTEMS_TOOL_VERSION "rtems$${RTEMS_MAJOR}")
set(RTEMS_TOOL_PREFIX "$${RTEMS_ARCH}-$${RTEMS_TOOL_VERSION}-")

set(CMAKE_C_COMPILER "$${RTEMS_TOOLS_TOP}/$${RTEMS_TOOL_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "$${RTEMS_TOOLS_TOP}/$${RTEMS_TOOL_PREFIX}g++")
set(CMAKE_ASM_COMPILER "$${RTEMS_TOOLS_TOP}/$${RTEMS_TOOL_PREFIX}gcc")
set(CMAKE_LINKER "$${RTEMS_TOOLS_TOP}/$${RTEMS_TOOL_PREFIX}ld")
set(CMAKE_AR "$${RTEMS_TOOLS_TOP}/$${RTEMS_TOOL_PREFIX}ar")
set(CMAKE_OBJCOPY "$${RTEMS_TOOLS_TOP}/$${RTEMS_TOOL_PREFIX}objcopy")
set(CMAKE_RTEMS_LD "$${RTEMS_TOOLS_TOP}/rtems-ld")
set(CMAKE_RTEMS_XSYMS "$${RTEMS_TOOLS_TOP}/rtems-xsyms")
set(CMAKE_RTEMS_SYMS "$${RTEMS_TOOLS_TOP}/rtems-syms")
set(CMAKE_DTC "$${RTEMS_TOOLS_TOP}/dtc")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# When testing $${CMAKE_C[XX]_COMPILER} functionality, don't try to link a test application
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS "${CFLAGS}")
set(CMAKE_CXX_FLAGS "${CFLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${LIBS}")
set(CMAKE_SHARED_LINKER_FLAGS "${LIBS} -Wl,--undefined -Wl,-r -nostdlib")
set(CMAKE_MODULE_LINKER_FLAGS "${LIBS} -Wl,--undefined -Wl,-r -nostdlib")
"""

class Target:
    """Represents a single RTEMS target, as defined by pkgconfig"""
    def __init__(self, pkgconfig_dir: str, arch: str, rtems: str, bsp: str):
        self.arch = arch
        self.rtems = rtems
        self.bsp = bsp
        self.pkgconfig_dir = pkgconfig_dir
        self._pkgconfig_parse()
    
    def _run_pkgconfig(self, args: list[str]) -> str | None:
        """Runs pkgconfig"""
        env = os.environ.copy()
        env['PKG_CONFIG_PATH'] = self.pkgconfig_dir
        r = subprocess.run(
            ['pkg-config'] + args,
            env=env,
            capture_output=True,
        )
        if r.returncode == 0:
            return r.stdout.decode().strip()
        return None
    
    def _pkgconfig_parse(self):
        """Uses pkgconfig to parse out the cflags, ldflags, etc."""
        self.cflags = self._run_pkgconfig(['--cflags', self.arch_bsp()])
        self.libs = self._run_pkgconfig(['--libs', self.arch_bsp()])
        self.vars = {x: self._run_pkgconfig([f'--variable={x}', self.arch_bsp()]) for x in [
            'RTEMS_MAJOR',
            'RTEMS_MINOR',
            'RTEMS_REVISION',
            'RTEMS_BSP_FAMILY',
            'RTEMS_BSP_BASE',
            'RTEMS_BSP',
            'RTEMS_ARCH',
        ]}

    def arch_bsp(self):
        """Returns the arch bsp string, i.e. aarch64-rtems7-k26"""
        return f'{self.arch}-{self.rtems}-{self.bsp}'

    def __repr__(self):
        return str({
            'cflags': self.cflags,
            'libs': self.libs,
            'bsp': self.arch_bsp()
        })

    def match_bsp(self, name: str) -> bool:
        """Matches this target against a BSP specification"""
        if name == self.arch_bsp():
            return True
        if name == f'{self.arch}/{self.bsp}' or name == f'{self.arch}-{self.bsp}':
            return True
        return False

    def generate_toolchain(self, rtems_top: str, rtems_tools_top: str) -> str:
        """
        Generates a CMake toolchain file for use with this BSP
        
        Parameters
        ----------
        rtems_top: str
            Path to the RTEMS install dir
        rtems_tools_top: str
            Path to the RTEMS tools install dir
        """
        vars = self.vars.copy()
        vars.update({
            'RTEMS_TOP': rtems_top,
            'RTEMS_TOOLS_TOP': rtems_tools_top,
            'CFLAGS': self.cflags,
            'LIBS': self.libs,
        })
        return string.Template(
            TOOLCHAIN_FRAGMENT
        ).substitute(
            vars
        )

def _find_pc_files(rtems_top: str) -> list[Target]:
    """Finds a list of targets from the specific pkgconfig directory"""
    targets = []
    pkgdir = f'{rtems_top}/lib/pkgconfig/'
    for k in os.listdir(pkgdir):
        fn = os.fsdecode(k)
        if not fn.endswith('.pc'): # Skip non-pkgconf files
            continue
        
        comps = fn.removesuffix('.pc').split('-')
        if len(comps) < 2:
            continue # Probably not what we want..
        arch = comps[0]
        rtems = comps[1]
        bsp = '-'.join(comps[2:])
        targets.append(Target(pkgdir, arch, rtems, bsp))
    return targets

def cmake_configure(parser: argparse.ArgumentParser, cmake_args: list[str] = [], features: dict = {}):
    parser.add_argument('--rtems-top', required=True, type=str, help='Path to the RTEMS installation directory')
    parser.add_argument('--rtems-tools', required=True, type=str, help='Path to the RTEMS tools installation directory')
    parser.add_argument('--rtems-arches', type=str, default=None, help='List of architectures to build for')
    parser.add_argument('--rtems-bsps', type=str, default=None, help='List of RTEMS BSPs to build for')
    parser.add_argument('--list-bsps', action='store_true', help='Show list of available BSPs')
    parser.add_argument('--print-toolchain', action='store_true', help='Dump a CMake toolchain to stdout')
    parser.add_argument('--build-dir', type=str, default='build', help='Path to the build directory')
    parser.add_argument('remaining', nargs=argparse.REMAINDER)
    
    # Add args for feature flags
    for k, v in features.items():
        # Enable/disable flags (bools)
        if v['type'] == 'bool':
            parser.add_argument(f'--enable-{k}', action='store_true', help=v.get('help', f'Enable {k}'))
            parser.add_argument(f'--disable-{k}', action='store_true', help=v.get('help', f'Disable {k}'))
        # Arbitrary string arguments
        elif v['type'] == 'str':
            parser.add_argument(f'--{k}', type=str, default=v.get('default', ''), choices=v.get('choices', None), help=v.get('help', k))

    args = parser.parse_args()

    # Parse arguments for feature flags
    for k, v in features.items():
        # Enable/disable flags (bools)
        if v['type'] == 'bool':
            if getattr(args, f'enable_{k.replace("-", "_")}'):
                cmake_args.append(f'-D{v["arg"]}=ON')
            elif getattr(args, f'disable_{k.replace("-", "_")}'):
                cmake_args.append(f'-D{v["arg"]}=OFF')
            else:
                cmake_args.append(f'-D{v["arg"]}={v.get("default", "ON")}')
        # Arbitrary string arguments
        elif v['type'] == 'str':
            cmake_args.append(f'-D{v["arg"]}=' + getattr(args, f'{k.replace("-","_")}', v.get("default")))

    arches = []
    if args.rtems_arches is not None:
        arches = args.rtems_arches.split(',')

    bsps = []
    if args.rtems_bsps is not None:
        bsps = args.rtems_bsps.split(',')

    toolchains: list[Target] = []
    for target in _find_pc_files(args.rtems_top):
        # Filter by arch
        if len(arches) > 0 and target.arch not in arches:
            continue
        # Filter by BSP
        if len(bsps) > 0 and not any([target.match_bsp(x) for x in bsps]):
            continue
        toolchains.append(target)

    # Generate a list?
    if args.list_bsps:
        for t in toolchains:
            print(t.arch_bsp())
        exit(0)

    # Dump toolchains to stdout?
    if args.print_toolchain:
        for t in toolchains:
            print(t.generate_toolchain(args.rtems_top, args.rtems_tools))
    
    os.makedirs(args.build_dir, exist_ok=True)
    
    # Generate toolchains into the build directory
    for t in toolchains:
        file = f'{args.build_dir}/{t.arch_bsp()}.cmake'
        with open(file, 'w') as fp:
            fp.write(t.generate_toolchain(args.rtems_top, args.rtems_tools))

    if '--' in args.remaining:
        args.remaining.remove('--')

    # Run the configure
    for t in toolchains:
        subprocess.run([
            'cmake',
            '.',
            f'-B{args.build_dir}/{t.arch_bsp()}',
            f'-DCMAKE_TOOLCHAIN_FILE={args.build_dir}/{t.arch_bsp()}.cmake'
        ] + cmake_args + args.remaining)


if __name__ == '__main__':
    cmake_configure(argparse.ArgumentParser())
